package Comunicacion;

public enum TiposMensaje {
	// Login
	LOGIN_REQUEST,
	LOGIN_RESPONSE,
	
	// Registro
	REGISTER_REQUEST,
	REGISTER_RESPONSE,
	
	GET_USUARIO_REQUEST,
	GET_USUARIO_RESPONSE,
	
	// Salas
	GET_SALAS_REQUEST,
	GET_SALAS_RESPONSE,
	
	CREATE_SALA_REQUEST,
	CREATE_SALA_RESPONSE,
	
	JOIN_SALA_REQUEST,
	JOIN_SALA_RESPONSE,
	
	QUIT_SALA_REQUEST,
	NOTIFICACION_CAMBIO_SALA,
	
	START_GAME_REQUEST,
	GAME_STARTED,
	
	// Game
	TAUNT,
	MENSAJE_INPUTS,
	MENSAJE_PARTIDA,
	GAME_FINISHED,
}
