package Comunicacion;

public enum TiposMensaje {
	// Login
	LOGIN_REQUEST,
	LOGIN_RESPONSE,
	
	// Registro
	REGISTER_REQUEST,
	REGISTER_RESPONSE,
	
	// Salas
	GET_SALAS_REQUEST,
	GET_SALAS_RESPONSE,
	
	CREATE_SALA_REQUEST,
	CREATE_SALA_RESPONSE,
	
	JOIN_SALA_REQUEST,
	JOIN_SALA_RESPONSE,
	
	USUARIO_NUEVO_EN_SALA,
	USUARIO_SALE_DE_SALA,
	
	START_GAME_REQUEST,
	GAME_STARTED,
	
	// Game
	MENSAJE_INPUTS,
	MENSAJE_PARTIDA,
}
