package Comunicacion;

public enum TiposMensaje {
	// Login
	LOGIN_REQUEST,
	LOGIN_RESPONSE,
	// Registro
	REGISTER_REQUEST,
	REGISTER_RESPONSE,
	// Salas
	GET_SALAS_REQUEST,
	GET_SALAS_RESPONSE,
	CREATE_SALA_REQUEST,
	CREATE_SALA_RESPONSE,
	JOIN_SALA_REQUEST,
	// Game
	START_GAME_REQUEST,
	RECIBIR_INPUTS,
	ENVIO_PARTIDA_ACTUAL,
}
